# Generated by Django 4.2.5 on 2023-09-23 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalanalytics', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Todo',
            new_name='RentalAnalysis',
        ),
    ]
