

Resources:
  RentalAnalysisFunction:
    Type: AWS::Lambda::Function
    Properties: 
      Architectures: 
        - x86_64
      Code: 
        Code
      CodeSigningConfigArn: String
      # DeadLetterConfig: 
      #   DeadLetterConfig
      Description: 'Function to run the rental analysis and export to excel'
      # Environment: 
      #   Environment
      EphemeralStorage: 
        EphemeralStorage
      FileSystemConfigs: 
        - FileSystemConfig
      FunctionName: String
      Handler: String
      ImageConfig: 
        ImageConfig
      KmsKeyArn: String
      Layers: 
        - String
      MemorySize: 250
      PackageType: String
      ReservedConcurrentExecutions: Integer
      Role: String
      Runtime: String
      RuntimeManagementConfig: 
        RuntimeManagementConfig
      SnapStart: 
        SnapStart
      Tags: 
        - Tag
      Timeout: Integer
      TracingConfig: 
        TracingConfig
      VpcConfig: 
        VpcConfig
  
  OutputWithFileLink:
    Type: AWS::SNS::Topic
    Properties: 
      ContentBasedDeduplication: Boolean
      DataProtectionPolicy: Json
      DisplayName: String
      FifoTopic: Boolean
      KmsMasterKeyId: String
      SignatureVersion: String
      Subscription: 
        - Subscription
      Tags: 
        - Tag
      TopicName: String
      TracingConfig: String