# Generated by Django 4.2.5 on 2023-09-23 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150)),
                ('price', models.CharField(max_length=500)),
                ('size', models.CharField(max_length=500)),
                ('pricePerSqft', models.CharField(max_length=500)),
            ],
        ),
    ]
