# Generated by Django 4.2.5 on 2023-12-23 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rentalanalytics', '0002_rename_todo_rentalanalysis'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RentalAnalysis',
            new_name='RentalProperties',
        ),
    ]
